/* eslint-disable */
// GENERATED by scripts/fetch-lpc.mjs — do not edit by hand.
// Mirrors client/public/lpc/manifest.json so the server can validate looks.

export interface WardrobePart {
  id: string;
  slot: string;
  name: string;
  rarity: string;
  base: boolean;
  variants: string[];
}

export const WARDROBE: WardrobePart[] = [
 {
  "id": "body",
  "slot": "body",
  "name": "body",
  "rarity": "starter",
  "base": true,
  "variants": [
   "amber",
   "black",
   "bronze",
   "brown",
   "light",
   "olive",
   "taupe"
  ]
 },
 {
  "id": "head",
  "slot": "head",
  "name": "head",
  "rarity": "starter",
  "base": true,
  "variants": [
   "amber",
   "black",
   "bronze",
   "brown",
   "light",
   "olive",
   "taupe"
  ]
 },
 {
  "id": "eyes",
  "slot": "eyes",
  "name": "eyes",
  "rarity": "starter",
  "base": true,
  "variants": [
   "blue",
   "brown",
   "gray",
   "green",
   "orange",
   "purple"
  ]
 },
 {
  "id": "hair.afro",
  "slot": "hair",
  "name": "afro",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.bob",
  "slot": "hair",
  "name": "bob",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.bob_side_part",
  "slot": "hair",
  "name": "side bob",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.braid",
  "slot": "hair",
  "name": "braid",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.bunches",
  "slot": "hair",
  "name": "bunches",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.buzzcut",
  "slot": "hair",
  "name": "buzzcut",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.curly_long",
  "slot": "hair",
  "name": "long curls",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.curly_short",
  "slot": "hair",
  "name": "short curls",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.cornrows",
  "slot": "hair",
  "name": "cornrows",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.long_straight",
  "slot": "hair",
  "name": "long straight",
  "rarity": "starter",
  "base": false,
  "variants": [
   "black",
   "blonde",
   "blue",
   "pink",
   "purple"
  ]
 },
 {
  "id": "hair.long_messy",
  "slot": "hair",
  "name": "long messy",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.messy1",
  "slot": "hair",
  "name": "messy",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.pixie",
  "slot": "hair",
  "name": "pixie",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.ponytail",
  "slot": "hair",
  "name": "ponytail",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.high_ponytail",
  "slot": "hair",
  "name": "high ponytail",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.pigtails",
  "slot": "hair",
  "name": "pigtails",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.spiked",
  "slot": "hair",
  "name": "spiked",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.twists_fade",
  "slot": "hair",
  "name": "twists",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.dreadlocks_long",
  "slot": "hair",
  "name": "dreadlocks",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.page",
  "slot": "hair",
  "name": "page",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.princess",
  "slot": "hair",
  "name": "princess",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.half_up",
  "slot": "hair",
  "name": "half up",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.swoop",
  "slot": "hair",
  "name": "swoop",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.wavy",
  "slot": "hair",
  "name": "wavy",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.idol",
  "slot": "hair",
  "name": "idol",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "hair.lob",
  "slot": "hair",
  "name": "lob",
  "rarity": "starter",
  "base": false,
  "variants": [
   "ash",
   "black",
   "blonde",
   "blue",
   "chestnut",
   "pink",
   "platinum",
   "purple",
   "redhead",
   "white"
  ]
 },
 {
  "id": "torso.shortsleeve",
  "slot": "torso",
  "name": "tee",
  "rarity": "starter",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "torso.tshirt",
  "slot": "torso",
  "name": "plain tee",
  "rarity": "starter",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "torso.shortsleeve_polo",
  "slot": "torso",
  "name": "polo",
  "rarity": "common",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "torso.longsleeve",
  "slot": "torso",
  "name": "longsleeve",
  "rarity": "starter",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "torso.laced",
  "slot": "torso",
  "name": "laced top",
  "rarity": "common",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "torso.sleeveless",
  "slot": "torso",
  "name": "tank top",
  "rarity": "starter",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "torso.blouse",
  "slot": "torso",
  "name": "blouse",
  "rarity": "starter",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "torso.blouse_longsleeve",
  "slot": "torso",
  "name": "long blouse",
  "rarity": "common",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "torso.vest",
  "slot": "torso",
  "name": "vest",
  "rarity": "common",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "torso.vest_open",
  "slot": "torso",
  "name": "open vest",
  "rarity": "common",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "torso.tunic",
  "slot": "torso",
  "name": "tunic",
  "rarity": "common",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "torso.tunic_sara",
  "slot": "torso",
  "name": "belted tunic",
  "rarity": "rare",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "torso.corset",
  "slot": "torso",
  "name": "corset",
  "rarity": "rare",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "torso.robe",
  "slot": "torso",
  "name": "robe",
  "rarity": "epic",
  "base": false,
  "variants": [
   "black",
   "blue",
   "purple",
   "red",
   "white"
  ]
 },
 {
  "id": "hat.bandana",
  "slot": "hat",
  "name": "bandana",
  "rarity": "starter",
  "base": false,
  "variants": [
   "black",
   "blue",
   "brown",
   "forest",
   "green",
   "leather",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "hat.tied",
  "slot": "hat",
  "name": "headband",
  "rarity": "starter",
  "base": false,
  "variants": [
   "black",
   "blue",
   "brown",
   "forest",
   "green",
   "leather",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "hat.feather_cap",
  "slot": "hat",
  "name": "feather cap",
  "rarity": "common",
  "base": false,
  "variants": [
   "black",
   "blue",
   "brown",
   "forest",
   "green",
   "leather",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "hat.hood",
  "slot": "hat",
  "name": "hood",
  "rarity": "common",
  "base": false,
  "variants": [
   "black",
   "blue",
   "brown",
   "forest",
   "green",
   "leather",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "hat.hijab",
  "slot": "hat",
  "name": "hijab",
  "rarity": "starter",
  "base": false,
  "variants": [
   "black",
   "blue",
   "brown",
   "forest",
   "green",
   "leather",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "hat.bowler",
  "slot": "hat",
  "name": "bowler",
  "rarity": "common",
  "base": false,
  "variants": [
   "black",
   "blue",
   "brown",
   "forest",
   "green",
   "leather",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "hat.tophat",
  "slot": "hat",
  "name": "top hat",
  "rarity": "rare",
  "base": false,
  "variants": [
   "black",
   "blue",
   "brown",
   "forest",
   "green",
   "leather",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "hat.tiara",
  "slot": "hat",
  "name": "tiara",
  "rarity": "epic",
  "base": false,
  "variants": [
   "black",
   "blue",
   "brown",
   "forest",
   "gold",
   "green",
   "leather",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "steel",
   "white",
   "yellow"
  ]
 },
 {
  "id": "hat.crown",
  "slot": "hat",
  "name": "crown",
  "rarity": "legendary",
  "base": false,
  "variants": [
   "black",
   "blue",
   "brown",
   "forest",
   "gold",
   "green",
   "leather",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "steel",
   "white",
   "yellow"
  ]
 },
 {
  "id": "hat.christmas",
  "slot": "hat",
  "name": "santa hat",
  "rarity": "rare",
  "base": false,
  "variants": [
   "black",
   "blue",
   "brown",
   "forest",
   "green",
   "leather",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "hat.elf",
  "slot": "hat",
  "name": "elf hat",
  "rarity": "rare",
  "base": false,
  "variants": [
   "black",
   "blue",
   "brown",
   "forest",
   "green",
   "leather",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "legs.pants",
  "slot": "legs",
  "name": "pants",
  "rarity": "starter",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "legs.pants2",
  "slot": "legs",
  "name": "straight pants",
  "rarity": "starter",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "legs.cuffed",
  "slot": "legs",
  "name": "cuffed jeans",
  "rarity": "starter",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "legs.shorts",
  "slot": "legs",
  "name": "shorts",
  "rarity": "starter",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "legs.short_shorts",
  "slot": "legs",
  "name": "short shorts",
  "rarity": "common",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "legs.leggings",
  "slot": "legs",
  "name": "leggings",
  "rarity": "starter",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "legs.leggings2",
  "slot": "legs",
  "name": "ribbed leggings",
  "rarity": "common",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "legs.hose",
  "slot": "legs",
  "name": "hose",
  "rarity": "common",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "legs.pantaloons",
  "slot": "legs",
  "name": "pantaloons",
  "rarity": "common",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "legs.plain",
  "slot": "legs",
  "name": "skirt",
  "rarity": "starter",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "legs.straight",
  "slot": "legs",
  "name": "pencil skirt",
  "rarity": "common",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "legs.slit",
  "slot": "legs",
  "name": "slit skirt",
  "rarity": "rare",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "legs.overskirt",
  "slot": "legs",
  "name": "overskirt",
  "rarity": "rare",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "legs.belle",
  "slot": "legs",
  "name": "belle skirt",
  "rarity": "rare",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "legs.formal",
  "slot": "legs",
  "name": "formal trousers",
  "rarity": "common",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "legs.formal_striped",
  "slot": "legs",
  "name": "striped trousers",
  "rarity": "rare",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "legs.fur",
  "slot": "legs",
  "name": "fur leggings",
  "rarity": "epic",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "feet.shoes",
  "slot": "feet",
  "name": "shoes",
  "rarity": "starter",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "feet.shoes2",
  "slot": "feet",
  "name": "loafers",
  "rarity": "starter",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "feet.sandals",
  "slot": "feet",
  "name": "sandals",
  "rarity": "starter",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "feet.slippers",
  "slot": "feet",
  "name": "slippers",
  "rarity": "starter",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "feet.boots",
  "slot": "feet",
  "name": "boots",
  "rarity": "common",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "feet.boots2",
  "slot": "feet",
  "name": "tall boots",
  "rarity": "common",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "feet.ghillies",
  "slot": "feet",
  "name": "ghillies",
  "rarity": "rare",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "feet.ankle",
  "slot": "feet",
  "name": "ankle socks",
  "rarity": "starter",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 },
 {
  "id": "feet.high",
  "slot": "feet",
  "name": "knee socks",
  "rarity": "common",
  "base": false,
  "variants": [
   "black",
   "blue",
   "forest",
   "green",
   "navy",
   "pink",
   "purple",
   "red",
   "rose",
   "sky",
   "white",
   "yellow"
  ]
 }
];
